server {
    listen 80;

    # Carpeta donde Nginx sirve los archivos estáticos construidos por Vue
    root /usr/share/nginx/html;
    index index.html index.htm;

    # Cualquier ruta que no exista como archivo debe regresar index.html
    # Esto permite SPA (Single Page Application) routing
    location / {
        try_files $uri /index.html;
    }

    # Proxy para login (Auth API)
    location /login {
        proxy_pass http://auth-api:8080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy para todos-api
    location /todos {
        proxy_pass http://todos-api:8082;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Proxy para Zipkin (si lo levantas)
    location /zipkin {
        proxy_pass http://zipkin:9411/api/v2/spans;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}
