jwt.secret=${JWT_SECRET}
server.port=8083

spring.application.name=users-api
spring.zipkin.baseUrl=http://127.0.0.1:9411/
spring.sleuth.sampler.percentage=100.0

spring.cache.redis.time-to-live=60000

spring.redis.host=${REDIS_HOST:redis}
spring.redis.port=${REDIS_PORT:6379}